baseURL = "https://www.andresmax.com/"
languageCode = "en-us"
title = "Andr√©s Max"
theme = "hugo-theme-cactus-plus"

googleAnalytics = "UA-2687767-4"
hasCJKLanguage = false

[params]
	name = "Andr√©s Max"
	description = "Describe your website"
	bio = "I design, make and break things."
	# Enter optionally your twitter account
	twitter = "andresmax"

	author = "Andr√©s Max"

	enableRSS = true
  enableToc = false

	enableMailchimp = true

	enableDisqus = false
	disqusShortname = "your_disqus_short_name"

	enableSummary = true
	useDescriptionReplaceSummary = false

	enableGoogleAnalytics = true
	enableBaiduAnalytics = false

	enableTwitterCard = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	youtube = "üì∫ Youtube"
	now = ""
	archive = ""
	subscribe = "RSS"

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = "Oh no!"
	subtitle404 = "The interwebs lost this."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/andresmax"
    github   = "https://www.github.com/andresmax"
    dribbble  = "https://www.dribbble.com/andresmax"
		instagram  = "https://instagram.com/andresmax"
		youtube  = "https://youtube.com/andresmax"
